# Generated by Django 4.1.7 on 2023-03-22 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_topic_room_user_message_room_topic"),
    ]

    operations = [
        migrations.RenameField(model_name="room", old_name="user", new_name="host",),
    ]
